# Generated by Django 4.1.7 on 2023-02-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollessons',
            name='title',
            field=models.CharField(default='test', max_length=128),
        ),
    ]
