# Generated by Django 4.1.7 on 2023-02-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_schoollessons_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollessons',
            name='date',
            field=models.DateField(),
        ),
    ]
