# Generated by Django 4.1.7 on 2023-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_schoollessons_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='pilotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolName', models.CharField(max_length=128)),
                ('title', models.CharField(default='test', max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('nbPerson', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
