# Generated by Django 4.1.7 on 2023-02-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_pilotevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='schoolLessons',
        ),
    ]
